name: Enviar correo electrónico

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Enviar correo electrónico
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        from: eduardoorm79@gmail.com  # Asegúrate de proporcionar la dirección de correo electrónico del remitente aquí
        to: gdgica1@gmail.com
        subject: "Asunto del correo electrónico"
        body: "Cuerpo del correo electrónico."
